Repository RohanNagar/thunder, pull requests merged in 2018-05, with the labels that each got.

#161 Enable dynamic URL injection in email messages
  api/src/test/java/com/sanction/thunder/models/UserTest.java
  application/src/main/java/com/sanction/thunder/resources/VerificationResource.java
  application/src/main/java/com/sanction/thunder/util/EmailUtilities.java
  application/src/main/resources/verification.html
  application/src/main/resources/verification.txt
  application/src/test/java/com/sanction/thunder/authentication/ThunderAuthenticatorTest.java
  application/src/test/java/com/sanction/thunder/dao/dynamodb/DynamoDbHealthCheckTest.java
  application/src/test/java/com/sanction/thunder/email/EmailModuleTest.java
  application/src/test/java/com/sanction/thunder/resources/VerificationResourceTest.java
  application/src/test/java/com/sanction/thunder/util/EmailUtilitiesTest.java
  checkstyle.xml
Labels: P1, Size: Medium, Type: Enhancement

#163 Supress logging in application unit tests
  application/src/test/resources/logback-test.xml
Labels: P3, Size: Small, Type: Testing

#164 Class Level Javadoc
  api/src/main/java/com/sanction/thunder/models/Email.java
  api/src/main/java/com/sanction/thunder/models/ResponseType.java
  api/src/main/java/com/sanction/thunder/models/User.java
  application/src/main/java/com/sanction/thunder/ThunderApplication.java
  application/src/main/java/com/sanction/thunder/ThunderComponent.java
  application/src/main/java/com/sanction/thunder/ThunderConfiguration.java
  application/src/main/java/com/sanction/thunder/ThunderModule.java
  application/src/main/java/com/sanction/thunder/authentication/Key.java
  application/src/main/java/com/sanction/thunder/authentication/ThunderAuthenticator.java
  application/src/main/java/com/sanction/thunder/dao/DaoModule.java
  application/src/main/java/com/sanction/thunder/dao/DatabaseError.java
  application/src/main/java/com/sanction/thunder/dao/DatabaseException.java
  application/src/main/java/com/sanction/thunder/dao/UsersDao.java
  application/src/main/java/com/sanction/thunder/dao/dynamodb/DynamoDbConfiguration.java
  application/src/main/java/com/sanction/thunder/dao/dynamodb/DynamoDbHealthCheck.java
  application/src/main/java/com/sanction/thunder/dao/dynamodb/DynamoDbModule.java
  application/src/main/java/com/sanction/thunder/dao/dynamodb/DynamoDbUsersDao.java
  application/src/main/java/com/sanction/thunder/email/EmailConfiguration.java
  application/src/main/java/com/sanction/thunder/email/EmailException.java
  application/src/main/java/com/sanction/thunder/email/EmailModule.java
  application/src/main/java/com/sanction/thunder/email/EmailService.java
  application/src/main/java/com/sanction/thunder/resources/UserResource.java
  application/src/main/java/com/sanction/thunder/resources/VerificationResource.java
  application/src/main/java/com/sanction/thunder/util/EmailUtilities.java
  application/src/main/java/com/sanction/thunder/validation/PropertyValidationRule.java
  application/src/main/java/com/sanction/thunder/validation/PropertyValidator.java
  application/src/test/java/com/sanction/thunder/authentication/ThunderAuthenticatorTest.java
  client/src/main/java/com/sanction/thunder/ThunderBuilder.java
  client/src/main/java/com/sanction/thunder/ThunderClient.java
Labels: Size: Medium, Type: Code Quality, Type: Documentation

#171 Junit5 migration
  api/pom.xml
  api/src/test/java/com/sanction/thunder/models/EmailTest.java
  api/src/test/java/com/sanction/thunder/models/ResponseTypeTest.java
  api/src/test/java/com/sanction/thunder/models/UserTest.java
  application/pom.xml
  application/src/test/java/com/sanction/thunder/ThunderApplicationTest.java
  application/src/test/java/com/sanction/thunder/ThunderConfigurationTest.java
  application/src/test/java/com/sanction/thunder/authentication/KeyTest.java
  application/src/test/java/com/sanction/thunder/authentication/ThunderAuthenticatorTest.java
  application/src/test/java/com/sanction/thunder/dao/DatabaseExceptionTest.java
  application/src/test/java/com/sanction/thunder/dao/UsersDaoTest.java
  application/src/test/java/com/sanction/thunder/dao/dynamodb/DynamoDbHealthCheckTest.java
  application/src/test/java/com/sanction/thunder/dao/dynamodb/DynamoDbUsersDaoTest.java
  application/src/test/java/com/sanction/thunder/email/EmailExceptionTest.java
  application/src/test/java/com/sanction/thunder/email/EmailModuleTest.java
  application/src/test/java/com/sanction/thunder/email/EmailServiceTest.java
  application/src/test/java/com/sanction/thunder/resources/UserResourceTest.java
  application/src/test/java/com/sanction/thunder/resources/VerificationResourceTest.java
  application/src/test/java/com/sanction/thunder/util/EmailUtilitiesTest.java
  application/src/test/java/com/sanction/thunder/validation/PropertyValidationRuleTest.java
  application/src/test/java/com/sanction/thunder/validation/PropertyValidatorTest.java
  checkstyle.xml
  client/pom.xml
  client/src/test/java/com/sanction/thunder/ThunderClientTest.java
  pom.xml
Labels: Size: Medium, Type: Code Quality, Type: Testing

#172 Enable more Email Configuration Options
  application/src/main/java/com/sanction/thunder/email/EmailConfiguration.java
  application/src/main/java/com/sanction/thunder/email/EmailModule.java
  application/src/main/java/com/sanction/thunder/email/MessageOptions.java
  application/src/main/java/com/sanction/thunder/email/MessageOptionsConfiguration.java
  application/src/main/java/com/sanction/thunder/resources/VerificationResource.java
  application/src/main/java/com/sanction/thunder/util/EmailUtilities.java
  application/src/test/java/com/sanction/thunder/ThunderApplicationTest.java
  application/src/test/java/com/sanction/thunder/ThunderConfigurationTest.java
  application/src/test/java/com/sanction/thunder/email/EmailModuleTest.java
  application/src/test/java/com/sanction/thunder/email/MessageOptionsConfigurationTest.java
  application/src/test/java/com/sanction/thunder/email/MessageOptionsTest.java
  application/src/test/java/com/sanction/thunder/resources/VerificationResourceTest.java
  application/src/test/java/com/sanction/thunder/util/EmailUtilitiesTest.java
  application/src/test/resources/fixtures/config.yaml
  application/src/test/resources/fixtures/message-options-config.yaml
  config/cloud-dev-config.yaml
  config/local-dev-config.yaml
  config/prod-config.yaml
  config/test-config.yaml
Labels: P1, Size: Medium, Type: Enhancement

#176 Handle URL Placeholder Edge Cases
  application/src/main/java/com/sanction/thunder/email/EmailModule.java
  application/src/main/java/com/sanction/thunder/email/MessageOptions.java
  application/src/main/java/com/sanction/thunder/email/MessageOptionsConfiguration.java
  application/src/main/java/com/sanction/thunder/resources/VerificationResource.java
  application/src/test/java/com/sanction/thunder/email/EmailModuleTest.java
  application/src/test/java/com/sanction/thunder/email/MessageOptionsTest.java
  application/src/test/java/com/sanction/thunder/resources/VerificationResourceTest.java
Labels: P1, Size: Small, Type: Enhancement

#177 Refactor EmailService to Interface
  application/src/main/java/com/sanction/thunder/dao/DatabaseError.java
  application/src/main/java/com/sanction/thunder/dao/dynamodb/DynamoDbModule.java
  application/src/main/java/com/sanction/thunder/email/EmailModule.java
  application/src/main/java/com/sanction/thunder/email/EmailService.java
  application/src/main/java/com/sanction/thunder/email/ses/SesEmailService.java
  application/src/test/java/com/sanction/thunder/ThunderConfigurationTest.java
  application/src/test/java/com/sanction/thunder/dao/DatabaseErrorTest.java
  application/src/test/java/com/sanction/thunder/dao/dynamodb/DynamoDbConfigurationTest.java
  application/src/test/java/com/sanction/thunder/dao/dynamodb/DynamoDbModuleTest.java
  application/src/test/java/com/sanction/thunder/email/MessageOptionsConfigurationTest.java
  application/src/test/java/com/sanction/thunder/email/ses/SesEmailServiceTest.java
  application/src/test/resources/fixtures/configuration/dynamodb-config.yaml
  application/src/test/resources/fixtures/configuration/message-options-config.yaml
  application/src/test/resources/fixtures/configuration/thunder-config.yaml
Labels: Size: Small, Type: Code Quality, Type: Testing
