Repository RohanNagar/thunder, pull requests merged in 2018-08, with the labels that each got.

#234 Run integration tests against Docker image
  .gitlab-ci.yml
  config/docker-config.yaml
  docker-compose.yml
  scripts/lib/aws-client.js
  scripts/lib/test-cases.js
  scripts/tools/test-runner.js
Labels: P1, Size: Medium, Type: Testing

#235 Send email password match bug
  application/src/main/java/com/sanction/thunder/resources/VerificationResource.java
  application/src/test/java/com/sanction/thunder/resources/VerificationResourceTest.java
Labels: P1, Size: Small, Status: Available, Type: Bug, Type: Code Quality

#244 Fix bug with incorrect response message
  application/src/main/java/com/sanctionco/thunder/resources/UserResource.java
Labels: P0, Size: Small, Type: Bug

#246 Fix accidental deletion bug
  application/src/main/java/com/sanctionco/thunder/dao/dynamodb/DynamoDbUsersDao.java
  application/src/test/java/com/sanctionco/thunder/dao/dynamodb/DynamoDbUsersDaoTest.java
Labels: P0, Size: Small, Type: Bug

#247 Integration Tests from YAML Files
  .gitlab-ci.yml
  scripts/README.md
  scripts/lib/aws-client.js
  scripts/lib/response-handler.js
  scripts/lib/test-cases.js
  scripts/logo/editablefile.ai
  scripts/logo/logo.png
  scripts/logo/logomark.png
  scripts/logo/logomarkv2.png
  scripts/logo/vertical.png
  scripts/logo/verticalv2.png
  scripts/package-lock.json
  scripts/package.json
  scripts/resources/user_details.json
  scripts/tests/test-runner.js
  scripts/tests/tests.yaml
  scripts/tests/update-existing-email.yaml
  scripts/tools/default_user.json
  scripts/tools/integration-tests.sh
  scripts/tools/run-local-dependencies.js
  scripts/tools/run-thunder-command.js
  scripts/tools/test-runner.js
Labels: Size: Large, Type: Testing

#253 Change configuration option name from dynamo to database
  application/src/main/java/com/sanctionco/thunder/ThunderConfiguration.java
  application/src/test/resources/fixtures/configuration/thunder-config-disabled-email.yaml
  application/src/test/resources/fixtures/configuration/thunder-config.yaml
  config/cloud-dev-config.yaml
  config/docker-config.yaml
  config/local-dev-config-disabled-email.yaml
  config/local-dev-config.yaml
  config/local-dev-properties-config.yaml
  config/prod-config.yaml
  config/test-config.yaml
  scripts/kubernetes/thunder-config.yaml
Labels: P1, Size: Small, Type: Enhancement

#254 Https
  Dockerfile
  config/ca-chain.cert.pem
  config/dev-server.jks
  config/local-dev-config.yaml
Labels: P1, Size: Small, Type: Dev Tools, Type: Documentation, Type: Feature

#259 Add Nexus Staging Plugin
  README.md
  pom.xml
Labels: P0, Size: Small, Type: Releases

#261 Add More Integration Tests to Travis
  .travis.yml
  scripts/README.md
  scripts/ci/docker-integration-tests.sh
  scripts/ci/docker_push.sh
  scripts/tests/disabled-email/config.yaml
  scripts/tests/disabled-email/docker-compose.yml
  scripts/tests/disabled-email/tests.yaml
  scripts/tests/general/config.yaml
  scripts/tests/general/docker-compose.yml
  scripts/tests/general/tests.yaml
  scripts/tests/update-existing-email/config.yaml
  scripts/tests/update-existing-email/docker-compose.yml
  scripts/tests/update-existing-email/tests.yaml
  scripts/tools/integration-tests.sh
Labels: P1, Size: Medium, Type: Dev Tools
